FROM node:20-alpine AS frontend-builder
WORKDIR /app
COPY frontend/package*.json ./
RUN apk add --update python3 make g++ && npm install
COPY frontend/ ./
RUN npm run build

FROM golang:1.25-bookworm AS backend-builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
COPY --from=frontend-builder /app/static ./frontend/static
RUN env CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
    go build -a -tags netgo -ldflags '-linkmode external -extldflags -static -s -w' \
    -o ovpn-admin

FROM alpine:3.23
WORKDIR /app
COPY --from=backend-builder /app/ovpn-admin ./
RUN apk add --update bash easy-rsa openssl openvpn coreutils iptables iptables-legacy libcap && \
    ln -s /usr/share/easy-rsa/easyrsa /usr/local/bin && \
    wget https://github.com/pashcovich/openvpn-user/releases/download/v1.0.4/openvpn-user-linux-amd64.tar.gz -O - | tar xz -C /usr/local/bin && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*
RUN addgroup -S ovpnadmin && adduser -S -G ovpnadmin ovpnadmin && \
    chown -R ovpnadmin:ovpnadmin /app && \
    setcap cap_net_admin+ep /usr/sbin/xtables-nft-multi 2>/dev/null || true
USER ovpnadmin
