apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvpn-admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openvpn-admin.labels" . | nindent 4 }}
data:
  server.conf: |-
    user nobody
    group nogroup

    mode server
    tls-server
    dev tun
    proto {{ .Values.openvpn.proto }}-server
    port {{ .Values.openvpn.port }}
    management 127.0.0.1 8989

    tun-mtu 1500
    mssfix

    keepalive 10 60
    client-to-client
    persist-key
    persist-tun

    cipher AES-256-GCM
    tls-version-min 1.2
    duplicate-cn

    server {{ .Values.openvpn.network }} {{ .Values.openvpn.networkMask }}

    topology subnet
    push "topology subnet"
    push "route-metric 9999"

    verb {{ .Values.openvpn.logLevel }}

    ifconfig-pool-persist /tmp/openvpn.ipp
    status /tmp/openvpn.status

    key-direction 0

    ca   /etc/openvpn/pki/ca.crt
    key  /etc/openvpn/pki/private/server.key
    cert /etc/openvpn/pki/issued/server.crt
    dh   /etc/openvpn/pki/dh.pem
    crl-verify /etc/openvpn/pki/crl.pem
    tls-auth /etc/openvpn/pki/ta.key

    {{- if .Values.ovpnAdmin.ccdEnabled }}
    client-config-dir /etc/openvpn/ccd
    {{- end }}
