{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openvpn-admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openvpn-admin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.hostname }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ include "openvpn-admin.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openvpn-admin.fullname" . }}
                port:
                  name: http
  {{- end }}
{{- end }}
